#pragma config(Sensor, in1,    powerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  quadLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  mgDetect,       sensorTouch)
#pragma config(Sensor, dgtl5,  LEDgreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  LEDyellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDred,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  progSkills,     sensorTouch)
#pragma config(Sensor, dgtl11, quadRight,      sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftCLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMGLift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           drvTopLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           drvBottomLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           drvBottomRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           drvTopRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightMGLift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightCLift,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

bool killSwitchState;

#include "Vex_Competition_Includes.c"
#include "constants.h"
#include "settings.h"
#include "control.h"
#include "autons.h"

// Pre Auton
//   Executes before auton; must return for auton to start.

void pre_auton() {

  	bStopTasksBetweenModes = true;         // Allow competition modes to control tasks.
	bDisplayCompetitionStatusOnLcd = true; // Use default LCD output from competition.

  // clearing encoders, setting servo positions, etc
}

// Autonomous Task
task autonomous() {

	writeDebugStreamLine("Autonomous program initiated.");
	setLEDs(0, 1, 0);

	if (!NO_AUTONOMOUS_WHATSOEVER) {

		if (SensorValue[progSkills] == 1) {
			auton60();
		} else if (ENABLE_MATCH_AUTON) {
			auton15();
		}

	}

	writeDebugStreamLine("Autonomous program execution complete.");

	setLEDs(1, 1, 0);

}

// User Control Task
task usercontrol() {

	writeDebugStreamLine("Driver mode activated.");

	killSwitchState = KS_DEFAULT;
	setLEDs(0, 0, 1);

	while (true) {

		if ( ((int)nPgmTime) % 10000 == 0) writeDebugStreamLine("Battery Voltage: %f", nImmediateBatteryLevel / 1000.0);

		if (!killSwitch()) {
			driveControl();
			mgLiftControl();
			coneLiftControl();
			encoderControl();
		} else {
			halt();
		}
	}
}
