#pragma config(Motor,  port2,           leftClawMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftArmMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           drvFrontLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           drvBackLeft,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           drvBackRight,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           drvFrontRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightArmMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightClawMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

bool killSwitchState;

#include "Vex_Competition_Includes.c"
#include "constants.h"
#include "control.c"

// Pre Auton
//   Executes before auton; must return for auton to start.

void pre_auton(){

  bStopTasksBetweenModes = true;         // Allow competition modes to control tasks.
	bDisplayCompetitionStatusOnLcd = true; // Use default LCD output from competition.

  // clearing encoders, setting servo positions, etc
}

// Autonomous Task
task autonomous(){

  AutonomousCodePlaceholderForTesting();

}

// User Control Task
task usercontrol(){

	killSwitchState = true;

  while (true) {
    if (!killSwitch()) {
    	armControl();
    	driveControl();
    	clawControl();
    } else {
    	halt();
    }
  }
}
